#!/usr/bin/env bash
# This script generates a mysqldump and creates an archive with it
mysqldump --all-databases -uroot -p "$1"  > backup.sql
current_date=$(date "+%d-%m-%Y")
tar -czvf "$current_date.tar.gz" backup.sql
