#!/usr/bin/env bash
# TO INFINITY AND BEYOND
echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; echo $$ | xargs kill -9' SIGTERM
trap 'rm /var/run/myscript.pid; echo $$ | xargs kill -9' SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT
while true
do
echo "To infinity and beyond"
sleep 2
done
