#!/usr/bin/env bash
# This script displays "Best School" 10 times
for ((i=1; i<=100; i++))
do
	let "modfive = $i % 5"
	let "modthree = $i % 3"
	if [ $modfive -eq 0 -a $modthree -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $modthree -eq 0 ]
	then
		echo "Fizz"
	elif [ $modfive -eq 0 ]
	then
		echo "Buzz"
	else
		echo $i
	fi
done
