#!/usr/bin/env bash
# This script displays the content of current directory
#+ in a list format
#+ where only the part after the first dash is displayed
LIST=$(ls)
for dir in $LIST
do
	echo "$dir" | cut -d "-" -f 2-
done
