#!/usr/bin/env bash
# This script displays the content of current directory
#+ in a list format
#+ where only the part after the first dash is displayed
for dir in `ls`
do
	echo $dir | cut -d "-" -f 2-
done
